import { useState } from 'react';
import { RotateCcw, Sparkles } from 'lucide-react';
import type { Insight } from '../../lib/types';
import { monthLabel } from '../../lib/format';
import { useStore } from '../../lib/store';
import { PageHeader } from '../../components/PageHeader';
import { Button } from '../../components/ui/Button';
import { Badge, Modal, Skeleton } from '../../components/ui/Feedback';
import { AiNote, InsightCard } from '../../components/Finance';

export default function Insights() {
  const { insights, cat, toast } = useStore();
  const [viewing, setViewing] = useState<Insight | null>(null);
  const [generating, setGenerating] = useState(false);
  const [current, ...archive] = insights;

  return (
    <div className="space-y-6">
      <PageHeader title="AI Insights" subtitle="Each month, Campus Coin AI reads your spending and explains it in plain words, with one small thing to try."
        actions={<Button variant="ai" loading={generating} icon={<RotateCcw className="h-4 w-4" />}
          onClick={() => { setGenerating(true); setTimeout(() => { setGenerating(false); toast('Your September insight is up to date.', 'info'); }, 1400); }}>
          Refresh this month
        </Button>} />

      <section aria-label="This month">
        {generating ? (
          <div className="rounded-card border border-lavender/40 bg-lavender-soft/50 p-6 dark:bg-lavender/[.06]">
            <p className="flex items-center gap-2 text-sm font-bold text-ai"><Sparkles className="h-4 w-4 animate-pulse" /> Reading 24 transactions from September…</p>
            <Skeleton className="mt-4 h-6 w-3/4" /><Skeleton className="mt-3 h-4 w-1/2" /><Skeleton className="mt-6 h-20" />
          </div>
        ) : <InsightCard insight={current} featured onView={() => setViewing(current)} />}
        <AiNote className="mt-2.5 px-1" />
      </section>

      <section aria-label="Past insights">
        <h2 className="mb-4 text-lg font-bold">Previous months</h2>
        <div className="grid gap-5 md:grid-cols-2">
          {archive.map((i) => <InsightCard key={i.id} insight={i} onView={() => setViewing(i)} />)}
        </div>
      </section>

      <Modal open={!!viewing} onClose={() => setViewing(null)} title={viewing ? `${monthLabel(viewing.month, true)} summary` : ''} subtitle="Generated by Campus Coin AI">
        {viewing && (
          <div className="space-y-4">
            <div><p className="text-xs font-bold text-muted">Summary</p><p className="mt-1">{viewing.summary}</p></div>
            <div><p className="text-xs font-bold text-muted">Notable pattern</p><p className="mt-1">{viewing.pattern}</p>
              <Badge tone={viewing.change > 0 ? 'neg' : 'pos'} className="mt-2">{cat(viewing.categoryId)?.name} {viewing.change > 0 ? '+' : ''}{viewing.change}% vs your average</Badge></div>
            <div className="rounded-2xl bg-lavender-soft/70 p-4 dark:bg-lavender/10"><p className="text-xs font-bold text-ai">Suggested action</p><p className="mt-1 font-semibold">{viewing.action}</p></div>
            <AiNote />
          </div>
        )}
      </Modal>
    </div>
  );
}
